### ISSUE TITLE
Can't Uploading files above 8mbs 

### ISSUE THREAD

**Issue by Alscof** [dissorial/pdf-chatbot#38]
It seems it's uploading only very small files. It will be awesome if also you fixed the previous authenticated version. Like upload both the old and new versions. Also It's not good at answering slight broad questions which makes it seem dumb or useless at times. But thanks for the update.

**Comment by dissorial** [comment]
Yes, I implemented a limit on file size for the deployed version. If you are running this locally, you can change the maximum file size for uploads. As for answering broader questions -- I suggest playing around with the prompt, chunk length, chunk overlap, and model temperature.

**Comment by kaiqiangh** [comment]
> 

where  can I change the maximum file size for uploads? Thanks

**Comment by kaiqiangh** [comment]
Just modified the nginx conf and the it works.
`client_max_body_size 50m;
client_body_buffer_size 50m;`
