### ISSUE TITLE
Question about storage location

### ISSUE THREAD

**Issue by kaiqiangh** [dissorial/pdf-chatbot#40]
Thanks forsharing this great repo.

I have a quick question. why does the latest version of this repo use localStorage instead of MongoDB? Privacy information is leaked if using local one. Thanks.

Kind regards.
Kai

**Comment by dissorial** [comment]
Because it seeems like the percentage of people who want to run this locally is significantly greater than the percentage of people who want to deploy this app. If someone wants to run this locally, then setting up mongodb, nextauth/google-auth and other things would be an unnecessary step.

**Comment by kaiqiangh** [comment]
Thanks for your reply!
